-- MySQL Script generated by MySQL Workbench
-- Fri Sep 29 00:12:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bk9kjvgo2gjf3qeyk1dt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bk9kjvgo2gjf3qeyk1dt` ;

-- -----------------------------------------------------
-- Schema bk9kjvgo2gjf3qeyk1dt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bk9kjvgo2gjf3qeyk1dt` DEFAULT CHARACTER SET utf8 ;
USE `bk9kjvgo2gjf3qeyk1dt` ;

-- -----------------------------------------------------
-- Table `bk9kjvgo2gjf3qeyk1dt`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bk9kjvgo2gjf3qeyk1dt`.`Categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `img` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bk9kjvgo2gjf3qeyk1dt`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bk9kjvgo2gjf3qeyk1dt`.`Users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `img` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 48
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bk9kjvgo2gjf3qeyk1dt`.`Servers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bk9kjvgo2gjf3qeyk1dt`.`Servers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `img` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  `category_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `category_id` (`category_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `Servers_ibfk_1`
    FOREIGN KEY (`category_id`)
    REFERENCES `bk9kjvgo2gjf3qeyk1dt`.`Categories` (`id`),
  CONSTRAINT `Servers_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `bk9kjvgo2gjf3qeyk1dt`.`Users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bk9kjvgo2gjf3qeyk1dt`.`Channels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bk9kjvgo2gjf3qeyk1dt`.`Channels` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `server_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `server_id` (`server_id` ASC) VISIBLE,
  CONSTRAINT `Channels_ibfk_1`
    FOREIGN KEY (`server_id`)
    REFERENCES `bk9kjvgo2gjf3qeyk1dt`.`Servers` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bk9kjvgo2gjf3qeyk1dt`.`Members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bk9kjvgo2gjf3qeyk1dt`.`Members` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `server_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `server_id` (`server_id` ASC) VISIBLE,
  CONSTRAINT `Members_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bk9kjvgo2gjf3qeyk1dt`.`Users` (`id`),
  CONSTRAINT `Members_ibfk_2`
    FOREIGN KEY (`server_id`)
    REFERENCES `bk9kjvgo2gjf3qeyk1dt`.`Servers` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bk9kjvgo2gjf3qeyk1dt`.`Messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bk9kjvgo2gjf3qeyk1dt`.`Messages` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_users` INT(11) NULL DEFAULT NULL,
  `id_channels` INT(11) NULL DEFAULT NULL,
  `content` TEXT NOT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `id_users` (`id_users` ASC) VISIBLE,
  INDEX `id_channels` (`id_channels` ASC) VISIBLE,
  CONSTRAINT `Messages_ibfk_1`
    FOREIGN KEY (`id_users`)
    REFERENCES `bk9kjvgo2gjf3qeyk1dt`.`Users` (`id`),
  CONSTRAINT `Messages_ibfk_2`
    FOREIGN KEY (`id_channels`)
    REFERENCES `bk9kjvgo2gjf3qeyk1dt`.`Channels` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
